name: Swift CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build and test (${{ matrix.os }} - Swift ${{ matrix.swift }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13]
        swift: ["5.9"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - name: Cache SwiftPM
        uses: actions/cache@v4
        with:
          path: |
            .build
            .swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v
      - name: Docker build (Linux only)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          if [ -f Dockerfile ]; then
            docker build -t kgproxy:ci .
          else
            echo "No Dockerfile present, skipping image build."
          fi